##  After learning so much in Numpy, It's time for an assignment. 

### You are a student and today is your Numpy test. The test will consist of 10 questions, purely related to code. You need to write code for the given questions.



In [1]:
import numpy as np

#### Q-1 Import Numpy and Write the code to know the version of numpy you are working on ?
Your output should look like this. <br>
NOTE : Numpy version may be different for you.

In [2]:
## write code here


In [3]:
np.__version__

'1.24.3'

#### Q - Create a numpy array having elements from 1 to 16 (inclusive) and print it.
Your output should look like this.

In [4]:
## write code here


In [5]:
ar=np.arange(1,17)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

#### Q-3 You need to filter the previous array in such a way that , it only contains odd values.
Note : You have to use boolean indexing.<br>
Your output should look like this.

In [6]:
## write code here


In [7]:
ar[ar%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

#### Q-4  Replace values that give remainder as 1 when divided by 2 from the above resulted array with 0
Your output should look like this.

In [8]:
## write code here


In [9]:
ar[ar % 2 == 0] =0
print (ar)


[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0]


#### Q-5  Change the shape of above resulted array to 4x4.
Your output should look like this.

In [10]:
## write code here


In [11]:
arr=ar.reshape(4, 4)
arr


array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-6 Stack the resulted array with itself vertically.
Your output should look like this.

In [12]:
## write code here


In [13]:
ar = np.vstack([arr, arr])
ar

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0],
       [ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0],
       [13,  0, 15,  0]])

#### Q-7 On this vertical stacked resulted array, reverse the column order in alternate manner. column new order = [ 2,1,4,3 ]
Your output should look like this.

In [14]:
## write code here


In [15]:
new=[1,0,3,2]
ar= ar[:, new]
ar

array([[ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15],
       [ 0,  1,  0,  3],
       [ 0,  5,  0,  7],
       [ 0,  9,  0, 11],
       [ 0, 13,  0, 15]])

#### Q-8 Calculate , mean , median and mode of the resulting array.
Your output should look like this.

In [16]:
## write code here


In [37]:
ar.mean()

4.0

In [38]:
np.median(ar)

0.5

In [39]:
s.mode(ar)

0

#### Q-9 Create an array of 5 values , that are selected at random from the above resulted array.
Your output should look like this.

In [ ]:
## write code here


In [23]:
ar=ar.flatten()
random_array=np.random.choice(ar,5,replace=False)
random_array

array([ 0, 11,  3, 15,  1])

#### Q-10 Complete the function, that calculate the value of this function (a.k.a Binary Cross Entropy) using  Vectorization.
`Given -
    y  : a vector of N dimension,
    y^ : a vector of N dimension
    N : elements in y and y^
    Use : log base 2
    `

<img src="BCE.png" width=500>

Your output should be : 0.011179895048277702

In [ ]:

    ## write code here
    

In [42]:
def binary_cross_entropy(y, y_hat):

    epsilon = 1e-15

    
    y_hat = np.clip(y_hat, epsilon, 1 - epsilon)

    bce = -1/N * np.sum(y * np.log2(y_hat) + (1 - y) * np.log2(1 - y_hat))

    return bce
y = np.array([1, 0, 1, 0])
y_hat = np.array([0.9, 0.2, 0.8, 0.1])

N = len(y)

binary_cross_entropy(y, y_hat)








0.2369655941662061